### ISSUE TITLE
Nullptr hits in BeamCal clusters

### ISSUE THREAD

**Issue by rete** [FCALSW/FCalClusterer#49] opened 2018-03-14 17:18 UTC
- OS version: SLC6
 - Compiler version: GCC 4.9
 - Package version: ilcsoft v01-19-05 from AFS + HEAD version of FCalClusterer
 - Goal: run the BeamCal reco for electrons
 - Reproduced by: 
```shell
# ilcsoft
source /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/init_ilcsoft.sh

# install head version of FCalClusterer
git clone https://github.com/FCALSW/FCalClusterer.git
cd FCalClusterer
mkdir build && cd build
cmake -C $ILCSOFT/ILCSoft.cmake ..
make install
cd ..

# update MARLIN_DLL with new FCalClusterer library (ugly way ...)
export MARLIN_DLL=/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/MarlinDD4hep/v00-05/lib/libMarlinDD4hep.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/DDMarlinPandora/v00-09-01/lib/libDDMarlinPandora.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/MarlinReco/v01-22/lib/libMarlinReco.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/PandoraAnalysis/v02-00-00/lib/libPandoraAnalysis.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/LCFIVertex/v00-07-04/lib/libLCFIVertexProcessors.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/CEDViewer/v01-15/lib/libCEDViewer.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/Overlay/v00-20/lib/libOverlay.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/MarlinFastJet/v00-05/lib/libMarlinFastJet.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/LCTuple/v01-10/lib/libLCTuple.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/MarlinKinfit/v00-05/lib/libMarlinKinfit.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/MarlinTrkProcessors/v02-09-01/lib/libMarlinTrkProcessors.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/MarlinKinfitProcessors/v00-03/lib/libMarlinKinfitProcessors.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/ILDPerformance/v01-04/lib/libILDPerformance.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/Clupatra/v01-02/lib/libClupatra.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/Physsim/v00-04/lib/libPhyssim.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/LCFIPlus/v00-06-07/lib/libLCFIPlus.so:$PWD/lib/libFCalClusterer.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/ForwardTracking/v01-13/lib/libForwardTracking.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/ConformalTracking/v01-04/lib/libConformalTracking.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/LICH/v00-01/lib/libLICH.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/MarlinTPC/v01-03/lib/libMarlinTPC.so:/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/v01-19-05/Garlic/v3.0.4/lib/libGarlic.so:

# ILDConfig with BeamCalReco running
git clone https://github.com/rete/ILDConfig.git
cd ILDConfig
git checkout beamcal-reco
cd StandardConfig/production

# run ddsim to get electrons
ddsim --compactFile $lcgeo_DIR/ILD/compact/ILD_l5_v02/ILD_l5_v02.xml \  
  --outputFile test_electrons.slcio \
  --steeringFile ddsim_steer.py \ 
  --runType batch \ 
  --enableGun \
  --gun.distribution uniform \
  --gun.particle e- \
  --gun.energy 50*GeV \
  --gun.thetaMax="44*mrad" \
  --gun.thetaMin="6*mrad" \
  --numberOfEvents 100

# Run Marlin to reconstruct electrons in BeamCal
Marlin --constant.lcgeo_DIR=$lcgeo_DIR \
  --constant.DetectorModel=ILD_l5_o1_v02 \
  --constant.OutputBaseName=BeamCalRecoHead_Test \
  --MyBeamCalClusterReco.CreateEfficiencyFile=true \
  --MyBeamCalClusterReco.EfficiencyFilename=BeamCalEfficiencyHeadTest.root \
  --global.LCIOInputFiles=test_electrons.slcio \
  --MyBeamCalClusterReco.Verbosity=DEBUG 
  MarlinStdReco.xml

```

This creates the output file `BeamCalRecoHead_Test_REC.slcio`. Dumping an event where you have a reconstructed cluster (some of them can contained in the BeamCal) shows this: 

```
 collection name : BCalClusters
 parameters: 

--------------- print out of Cluster collection --------------- 

  flag:  0x80000000
     LCIO::CLBIT_HITS : 1

 [   id   ] |type|  energy  |energyerr |      position ( x,y,z)           |  itheta  |   iphi   
------------|----|----------|----------|----------------------------------|----------|----------
 [00002274] |   0|+2.977e+01|+0.000e+00|-5.996e+01, +3.223e+01, +3.226e+03|+0.000e+00|+0.000e+00 errors (6 pos)/( 3 dir): (+0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, )/(+0.000e+00+0.000e+00+0.000e+00)
 clusters(e): 
 subdetector energies : +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +2.977e+01, 
 hits ->[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
 [00002275] |   0|+7.039e+00|+0.000e+00|+9.059e+01, +7.460e+01, +3.258e+03|+0.000e+00|+0.000e+00 errors (6 pos)/( 3 dir): (+0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, )/(+0.000e+00+0.000e+00+0.000e+00)
 clusters(e): 
 subdetector energies : +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +7.039e+00, 
 hits ->[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) 
[000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00) [000000+0](+1.00e+00)
...
```

All the hits are written as nullptr. 

Is there anything wrong in my settings ?

Cheers,
Remi

**Comment by andresailer** [comment] 2018-03-15 17:48
I can reproduce the problem with your configuration. But for the CLICreconstruction I get the correct links, so there is probably something wrong in your configuration, but I don't know what.
```
 collection name : BeamCalClusters
 parameters:

--------------- print out of Cluster collection ---------------

  flag:  0x80000000
     LCIO::CLBIT_HITS : 1

 [   id   ] |type|  energy  |energyerr |      position ( x,y,z)           |  itheta  |   iphi
------------|----|----------|----------|----------------------------------|----------|----------
 [00005251] |   0|+1.254e+03|+0.000e+00|-4.165e+00, -2.435e+01, -3.342e+03|+0.000e+00|+0.000e+00 errors (6 pos)/( 3 dir): (+0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, )/(+0.000e+00+0.000e+00+0.000e+00)
 clusters(e):
 subdetector energies : +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +0.000e+00, +1.254e+03,
 hits ->[000+8146](+1.00e+00) [000+8151](+1.00e+00) [000+8279](+1.00e+00) [00+10619](+1.00e+00)....
```

The hits are created and stored and they are in the output collection. They are correctly assigned to the cluster, but then suddenly they seem to disappear for the cluster,,,

**Comment by andresailer** [comment] 2018-03-15 18:43
I see a difference in the collection of BeamCalHits (the calorimeterHit collection created by BeamCalClusterReco
In your output I see
```
LCIO::RCHBIT_NO_PTR : 1
```
In my CLIC output I see
```
LCIO::RCHBIT_NO_PTR : 0
```

And the problem is a bug in setting the flags for the calorimeterhit collection

**Closed** 2018-03-16 07:49 UTC
